version: "3.4"

networks:
  default:
    external:
      name: overlay-net
    driver: overlay
    
services:
  postgresql:
    image: "docker.io/bitnami/postgresql:11-debian-10"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=iudx-postgresql
      - POSTGRESQL_DATABASE=iudx-postgresql-database
      
    volumes:
      - "postgresql_data:/bitnami/postgresql"
  keycloak:
    image: docker.io/bitnami/keycloak:12-debian-10
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=iudx-database
      - KEYCLOAK_DATABASE_USER=iudex-user
    depends_on:
      - postgresql
    volumes:
      - "$(pwd)"
volumes:
  postgresql_data:
    driver: local
